ALTER TABLE users ADD COLUMN IF NOT EXISTS login VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_login ON users(lower(login)) WHERE login IS NOT NULL;